### ISSUE TITLE
نمونه فعالیت ربات 

### ISSUE THREAD

**Issue by TonDevv** [amirmalek0/E-Commerce-Telegram-Bot#1]
درود. یک ربات فعال در تلگرام دارید که فعال باشه و ببینیم به چه صورت هست ؟

**Comment by TonDevv** [comment]
و امکان داره راه ارتباطی مثل تلگرام بدید ؟ یک پروژه دارم که هزینش رو پرداخت میکنم

**Comment by amirmalek0** [comment]
درود، ربات ([wordpressxbot](https://t.me/wordpressxbot)) در حال حاضر با همین سورس اجرا شده.

**Comment by TonDevv** [comment]
یک راه ارتباطی در تلگرام دارید ؟ قصد داریم یه پروژه روی همین سورس اجرا کنیم. بابت هزینه هم مشکلی ندارم.

**Comment by amirmalek0** [comment]
بله،میتونید از طریق آیدی زیر در ارتباط باشید.
@Khmv4tfti
